export const INDONESIA_REGIONS: Record<string, string[]> = {
  Aceh: ["Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Aceh Besar"],
  "Sumatera Utara": [
    "Medan",
    "Binjai",
    "Pematangsiantar",
    "Sibolga",
    "Deli Serdang",
  ],
  "Sumatera Barat": ["Padang", "Bukittinggi", "Payakumbuh", "Pariaman", "Agam"],
  Riau: ["Pekanbaru", "Dumai", "Kampar", "Siak", "Bengkalis"],
  "Kepulauan Riau": ["Batam", "Tanjungpinang", "Bintan", "Karimun", "Natuna"],
  Jambi: [
    "Jambi",
    "Sungai Penuh",
    "Muaro Jambi",
    "Bungo",
    "Tanjung Jabung Barat",
  ],
  "Sumatera Selatan": [
    "Palembang",
    "Prabumulih",
    "Lubuklinggau",
    "Pagar Alam",
    "Ogan Ilir",
  ],
  "Bangka Belitung": [
    "Pangkalpinang",
    "Belitung",
    "Belitung Timur",
    "Bangka",
    "Bangka Barat",
  ],
  Bengkulu: ["Bengkulu", "Rejang Lebong", "Bengkulu Selatan", "Kaur", "Seluma"],
  Lampung: [
    "Bandar Lampung",
    "Metro",
    "Lampung Selatan",
    "Lampung Tengah",
    "Pringsewu",
  ],
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Timur",
  ],
  Banten: ["Serang", "Cilegon", "Tangerang", "Tangerang Selatan", "Pandeglang"],
  "Jawa Barat": ["Bandung", "Bekasi", "Bogor", "Depok", "Cirebon"],
  "Jawa Tengah": ["Semarang", "Solo", "Magelang", "Tegal", "Pekalongan"],
  "DI Yogyakarta": [
    "Yogyakarta",
    "Sleman",
    "Bantul",
    "Kulon Progo",
    "Gunungkidul",
  ],
  "Jawa Timur": ["Surabaya", "Malang", "Kediri", "Madiun", "Sidoarjo"],
  Bali: ["Denpasar", "Badung", "Gianyar", "Tabanan", "Buleleng"],
  "Nusa Tenggara Barat": [
    "Mataram",
    "Bima",
    "Lombok Barat",
    "Lombok Tengah",
    "Sumbawa",
  ],
  "Nusa Tenggara Timur": [
    "Kupang",
    "Ende",
    "Maumere",
    "Sumba Timur",
    "Manggarai",
  ],
  "Kalimantan Barat": [
    "Pontianak",
    "Singkawang",
    "Kubu Raya",
    "Ketapang",
    "Sintang",
  ],
  "Kalimantan Tengah": [
    "Palangka Raya",
    "Kotawaringin Timur",
    "Kapuas",
    "Katingan",
    "Barito Selatan",
  ],
  "Kalimantan Selatan": [
    "Banjarmasin",
    "Banjarbaru",
    "Banjar",
    "Kotabaru",
    "Tanah Laut",
  ],
  "Kalimantan Timur": [
    "Samarinda",
    "Balikpapan",
    "Bontang",
    "Kutai Kartanegara",
    "Berau",
  ],
  "Kalimantan Utara": [
    "Tanjung Selor",
    "Tarakan",
    "Nunukan",
    "Malinau",
    "Bulungan",
  ],
  "Sulawesi Utara": [
    "Manado",
    "Bitung",
    "Tomohon",
    "Minahasa",
    "Bolaang Mongondow",
  ],
  Gorontalo: [
    "Gorontalo",
    "Bone Bolango",
    "Boalemo",
    "Pohuwato",
    "Gorontalo Utara",
  ],
  "Sulawesi Tengah": ["Palu", "Poso", "Donggala", "Parigi Moutong", "Banggai"],
  "Sulawesi Barat": [
    "Mamuju",
    "Majene",
    "Polewali Mandar",
    "Mamasa",
    "Pasangkayu",
  ],
  "Sulawesi Selatan": ["Makassar", "Parepare", "Palopo", "Gowa", "Bone"],
  "Sulawesi Tenggara": ["Kendari", "Baubau", "Kolaka", "Konawe", "Muna"],
  Maluku: ["Ambon", "Tual", "Maluku Tengah", "Buru", "Seram Bagian Barat"],
  "Maluku Utara": [
    "Ternate",
    "Tidore Kepulauan",
    "Halmahera Barat",
    "Halmahera Selatan",
    "Morotai",
  ],
  Papua: ["Jayapura", "Biak Numfor", "Keerom", "Sarmi", "Yahukimo"],
  "Papua Barat": ["Manokwari", "Sorong", "Fakfak", "Kaimana", "Teluk Bintuni"],
  "Papua Selatan": ["Merauke", "Boven Digoel", "Mappi", "Asmat"],
  "Papua Tengah": ["Nabire", "Mimika", "Paniai", "Intan Jaya", "Puncak"],
  "Papua Pegunungan": [
    "Jayawijaya",
    "Lanny Jaya",
    "Nduga",
    "Pegunungan Bintang",
    "Yalimo",
  ],
  "Papua Barat Daya": [
    "Kota Sorong",
    "Sorong",
    "Raja Ampat",
    "Tambrauw",
    "Maybrat",
  ],
};

export const INDONESIA_PROVINCES = Object.keys(INDONESIA_REGIONS);
